# service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-panda-jedi-service
  labels:
    app: panda-jedi-server
spec:
  type: ClusterIP     # NodePort
  ports:
   - name: panda-jedi-server-http
     protocol: TCP
     port: 25080
     targetPort: 25080
   - name: panda-jedi-server-https
     protocol: TCP
     port: 25443
     targetPort: 25443
  selector:
   app: panda-jedi-server
