apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb
data:
  UMASK: "0660"
  UMASK_DIR: "0750"
---
apiVersion: v1
kind: Secret
metadata:
  name: mariadb
data:
  password: bWFyaWFkYg==
  root-password: bWFyaWFkYg==
---
apiVersion: v1
kind: Secret
metadata:
  name: user
data:
  password: dXNlcg==

