#!/bin/bash

# docker build --build-arg TAG=$SOURCE_BRANCH -f $DOCKERFILE_PATH --network host --no-cache -t $IMAGE_NAME:$SOURCE_BRANCH .
# docker build --build-arg TAG=0.10.17 -f Dockerfile --network host --no-cache --tag wguanicedew/idds:0.10.17 .
# docker images
# docker login --username=wguanicedew
# docker push wguanicedew/idds:0.10.17

