# Default values for idds.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# idds_db, idds_user and idds_schema should not be changed currently
database:
  idds_db: &idds_db "idds_db"
  idds_user: &idds_user "idds"
  idds_password: &idds_password "MyPass123"
  idds_schema: &idds_schema "doma_idds"

main:
  enabled: true
  replicaCount: 1
  daemonReplicaCount: 1
  image:
    repository: wguanicedew/idds
    pullPolicy: "IfNotPresent"
    # Overrides the image tag whose default is the chart appVersion.
    # tag: "0.10.17.2"
    tag: "0.10.23.2"
  autoStart: true

  persistentvolume:
    enabled: true
    path: "/mnt/idds-main-logs"
    size: 5Gi
  hostcerts:
    enabled: false
  database:
    name: *idds_db
    user: *idds_user
    password: *idds_password
    schema: *idds_schema
  service:
    type: ClusterIP
    httpsPort: 443
  ingress:
    enabled: true
    hosts:
      - domain: cern.ch
        # hostOverride: idds-k8s-dev-jedi.cern.ch
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: idds-dev-main-tlssan-cert
        hosts:
          - domain: cern.ch
            # hostOverride: idds-k8s-dev-jedi.cern.ch
postgres:
  # nameOverride: {{ .Release.Name }}-postgres
  # fullnameOverride: {{ .Release.Name }}-postgres
  enabled: true
  persistentvolume:
    enabled: true
    path: "/mnt/idds-database"
    size: 5Gi
  image:
    repository: postgres
    pullPolicy: IfNotPresent
    tag: "13.6"

  database:
    name: *idds_db
    user: *idds_user
    password: *idds_password
    schema: *idds_schema
  ingress:
    enabled: true
    hosts:
      - domain: cern.ch
        # hostOverride: idds-k8s-dev-postgres.cern.ch
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: ""
        hosts:
          - domain: cern.ch
            # hostOverride: idds-k8s-dev-postgres.cern.ch
