apiVersion: mariadb.mmontes.io/v1alpha1
kind: MariaDB
metadata:
  name: mariadb
  namespace: iam-db
spec:
  rootPasswordSecretKeyRef:
    name: mariadb-admin
    key: password

  database: iam_db
  username: iam
  passwordSecretKeyRef:
    name: mariadb-user
    key: password

  image:
    repository: mariadb
    tag: "10.11"
    pullPolicy: IfNotPresent

  port: 3306

  volumeClaimTemplate:
    resources:
      requests:
        storage: 50Gi
    storageClassName: wekafs--sdf-k8s01
    accessModes:
      - ReadWriteOnce

  myCnf: |
    [mysqld]
    bind-address=0.0.0.0
    default_storage_engine=InnoDB
    binlog_format=row
    innodb_autoinc_lock_mode=2
    max_allowed_packet=256M
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 512Mi

  env:
    - name: TZ
      value: SYSTEM
    - name: MARIADB_BACKUP_RSA
      valueFrom:
        secretKeyRef:
          name: mariadb-backup
          key: mariadb_backup_rsa

  envFrom:
    - configMapRef:
        name: mariadb

  podSecurityContext:
    runAsUser: 0

  securityContext:
    allowPrivilegeEscalation: false
