# pv
kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ include "server.fullname" . }}
  labels:
      {{- include "server.labels" . | nindent 4 }}
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.persistentvolume.size }}
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{ .Values.persistentvolume.path }}
---
# pv claim
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "server.fullname" . }}
  labels:
    {{- include "server.labels" . | nindent 4 }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.persistentvolume.size }}
  selector:
    matchLabels:
      {{- include "server.selectorLabels" . | nindent 6 }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "server.fullname" . }}
  labels:
    {{- include "server.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "server.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "server.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{ if .Values.autoStart -}}
          command: [ "/bin/sh", "-c" ]
          args:
            - chmod +x /opt/panda/etc/configmap/setup_init.sh;
              /opt/panda/etc/configmap/setup_init.sh;
              /etc/rc.d/init.d/httpd-pandasrv start;
              sleep infinity & wait
          {{ end -}}
          ports:
            - name: http
              containerPort: 25080
              protocol: TCP
            - name: https
              containerPort: 25443
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
              # - name: {{ include "server.fullname" . }}-logs
              #  mountPath: /var/log/panda-server/
              - name: {{ include "server.fullname" . }}-configmap
                mountPath: /opt/panda/etc/configmap
              {{- if .Values.hostcerts.enabled -}}
              - name: {{ include "server.fullname" . }}-certs
                mountPath: /opt/panda/etc/cert
              {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: {{ include "server.fullname" . }}-logs
          persistentVolumeClaim:
            claimName: {{ include "server.fullname" . }}
        - name: {{ include "server.fullname" . }}-configmap
          configMap:
              name: {{ include "server.fullname" . }}-configmap
        {{- if .Values.hostcerts.enabled -}}
        - name: {{ include "server.fullname" . }}-certs
          configMap:
              name: {{ include "server.fullname" . }}-certs
        {{- end }}
