# Default values for iam.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  secret: "panda-secrets"
  sub_secret_name: "iam-mariadb"

main:
  enabled: true

  database:
    name: "test-db"

