{{- if .Values.idds.enabled }}
# iDDS configuration
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.idds.name }}-db-envs
type: Opaque
stringData:
  POSTGRES_DB: "{{ .Values.idds.database.name }}"
  POSTGRES_USER: "{{ .Values.idds.database.user }}"
  POSTGRES_PASSWORD: "{{ .Values.idds.database.password }}"
  POSTGRES_SCHEMA: "{{ .Values.idds.database.schema }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.idds.name }}-envs
type: Opaque
stringData:
  PANDA_AUTH_ID_TOKEN: "{{ .Values.global.authIdToken }}"
  PANDA_AUTH_VO: "{{ .Values.global.authVO }}"
  PANDA_AUTH: "{{ .Values.global.auth }}"

  IDDS_DATABASE_NAME: "{{ .Values.idds.database.name}}"
  IDDS_DATABASE_USER: "{{ .Values.idds.database.user}}"
  IDDS_DATABASE_PASSWORD: "{{ .Values.idds.database.password}}"
  IDDS_DATABASE_SCHEMA: "{{ .Values.idds.database.schema}}"
  IDDS_DATABASE_HOST: "{{ .Values.idds.database.host}}"

  IDDS_CONDUCTOR_BROKERS: "{{ join "," .Values.global.activemq.serverList }}"
  IDDS_CONDUCTOR_PORT: "{{default "61613" .Values.global.activemq.port }}"
  IDDS_CONDUCTOR_DESTINATION: "{{.Values.idds.activemq.destination}}"
  IDDS_CONDUCTOR_USERNAME: "{{.Values.idds.activemq.username}}"
  IDDS_CONDUCTOR_PASSWORD: "{{.Values.global.activemq.basePasswd}}_{{.Values.idds.activemq.username}}"

  IDDS_OIDC_RUBIN_CLIENT_ID: "{{.Values.global.oidc.rubin.client_id}}"
  IDDS_OIDC_RUBIN_CLIENT_SECRET: "{{.Values.global.oidc.rubin.client_secret}}"
  IDDS_OIDC_RUBIN_PRODUCTION_CLIENT_ID: "{{.Values.global.oidc.rubin_production.client_id}}"
  IDDS_OIDC_RUBIN_PRODUCTION_CLIENT_SECRET: "{{.Values.global.oidc.rubin_production.client_secret}}"
  IDDS_OIDC_PANDA_DEV_CLIENT_ID: "{{.Values.global.oidc.panda_dev.client_id}}"
  IDDS_OIDC_PANDA_DEV_CLIENT_SECRET: "{{.Values.global.oidc.panda_dev.client_secret}}"

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.idds.name }}-certs
type: Opaque
stringData:
  {{- range $path, $_ := .Files.Glob "files/idds_certs/**.pem" }}
  {{ base $path }}: |-
    {{ $.Files.Get $path | b64enc }}
  {{- end }}

{{- end }}
