{{- if .Values.panda.enabled }}
# panda configuration
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.panda.name }}-envs
type: Opaque
stringData:
  PANDA_DB_PASSWORD: {{ .Values.panda.database.password }}
  PANDA_DB_HOST: {{ .Values.panda.database.dbhost }}

  PANDA_AUTH_ID_TOKEN: {{ .Values.global.authIdToken }}
  PANDA_AUTH_VO: {{ .Values.global.authVO }}

  # ActiveMQ
  PANDA_ACTIVEMQ_LIST: {{ join "," .Values.global.activemq.serverList }}
  PANDA_ACTIVEMQ_PASSWD_panda: {{ .Values.global.activemq.basePasswd }}_panda
  PANDA_ACTIVEMQ_PASSWD_jedi: {{ .Values.global.activemq.basePasswd }}_jedi

  # iDDS
  PANDA_IDDS_HOST: "{{ .Values.global.idds.restHost }}"
  PANDA_IDDS_PORT: "{{ .Values.global.idds.restPort }}"
  PANDA_IDDS_AUTH_ID_TOKEN: "{{ .Values.global.authIdToken }}"
  PANDA_IDDS_AUTH_VO: "{{ .Values.global.authVO }}"
  
  # Rucio
  PANDA_RUCIO_HOST: "{{ .Values.global.rucio.rucioHost }}"
  PANDA_RUCIO_AUTH_HOST: "{{ .Values.global.rucio.authHost }}"
  PANDA_RUCIO_USERNAME: "{{ .Values.global.rucio.username }}"
  PANDA_RUCIO_PASSWORD: "{{ .Values.global.rucio.password }}"
  PANDA_RUCIO_ACCOUNT: "{{ .Values.global.rucio.account }}"

---
# certs
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.panda.name }}-certs
type: Opaque
stringData:
  {{- range $path, $_ := .Files.Glob "files/panda_certs/**.pem" }}
  {{ base $path }}: |-
    {{ $.Files.Get $path | b64enc }}
  {{- end }}

---
# auth
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.panda.name }}-auth
type: Opaque
stringData:
  {{- range $path, $_ := .Files.Glob "files/panda_auths/**_auth_config.json" }}
  {{ base $path }}: |-
    {{ $.Files.Get $path }}
  {{- end }}

{{- end }}
