
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "iam.fullname" . }}-configmap
  labels:
    {{- include "iam.labels" . | nindent 4 }}
data:
  IAM_JAVA_OPTS: "-Dspring.profiles.active=prod,google,saml"

