name: Test

on:
  pull_request:
  push:
    branches:
      - master

jobs:

  test:
    name: Test
    runs-on: ubuntu-20.04
    if: github.repository == 'traefik/traefik-helm-chart'
    env:
      TMPDIR: /tmp
      ARCH: amd64
      CATTLE_HELM_UNITTEST_VERSION: v0.1.6-rancher1

    steps:

      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install
        run: |
          curl -L https://git.io/get_helm.sh | bash -s -- -v v3.1.2
          curl -sSL -o /tmp/ct.tgz https://github.com/helm/chart-testing/releases/download/v3.5.0/chart-testing_3.5.0_linux_amd64.tar.gz
          tar xzf /tmp/ct.tgz -C /tmp && sudo cp /tmp/ct /usr/local/bin/ct && command -v ct

      - name: Make
        run: make
