NAME: iam-db-dev
LAST DEPLOYED: Wed May 17 03:10:01 2023
NAMESPACE: panda
STATUS: pending-install
REVISION: 1
TEST SUITE: None
HOOKS:
MANIFEST:
---
# Source: iam/charts/mariadb/templates/deployment.yaml
# pv claim
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: iam-db-dev-mariadb
  labels:
    helm.sh/chart: mariadb-0.1.0
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/instance: iam-db-dev
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  storageClassName: wekafs--sdf-k8s01
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
---
# Source: iam/charts/mariadb/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: iam-db-dev-mariadb
  labels:
    helm.sh/chart: mariadb-0.1.0
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/instance: iam-db-dev
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: mariadb-port
      protocol: TCP
      name: mariadb-port
  selector:
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/instance: iam-db-dev
---
# Source: iam/charts/mariadb/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iam-db-dev-mariadb
  labels:
    helm.sh/chart: mariadb-0.1.0
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/instance: iam-db-dev
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mariadb
      app.kubernetes.io/instance: iam-db-dev
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mariadb
        app.kubernetes.io/instance: iam-db-dev
    spec:
      hostname:  iam-db-dev
      serviceAccountName: default
      securityContext:
        {}
      containers:
        - name: mariadb
          securityContext:
            {}
          image: "bitnami/mariadb:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - name: mariadb-port
              containerPort: 3306
              protocol: TCP
          envFrom:
            - secretRef:
                name: panda-secrets-iam-db-envs
          resources:
            {}
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: iam-db-dev-mariadb-data
            - mountPath: /docker-entrypoint-initdb.d/
              name: iam-db-dev-mariadb-initdb
      volumes:
        - name: iam-db-dev-mariadb-data
          persistentVolumeClaim:
            claimName: iam-db-dev-mariadb
        - name: iam-db-dev-mariadb-initdb
          secret:
              secretName: panda-secrets-iam-initdb

