# Default values for bigmon.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# panda_db, panda_user and panda_schema should not be changed currently
database:
  panda_db: &panda_db "panda_db"
  panda_user: &panda_user "panda"
  panda_password: &panda_password "MyPass123"
  panda_schema: &panda_schema "doma_panda"

main:
  enabled: true
  replicaCount: 1
  image:
    repository: wguanicedew/bigmon
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "0.2.0"

  autoStart: true

  persistentvolume:
    path: "/mnt/panda-bigmon-logs"
    size: 5Gi
  hostcerts:
    enabled: false
  database:
    panda_db: *panda_db
    panda_user: *panda_user
    panda_password: *panda_password
    panda_schema: *panda_schema
  service:
    type: ClusterIP
    httpsPort: 443
  ingress:
    enabled: true
    hosts:
      - domain: cern.ch
        # hostOverride: panda-k8s-dev-jedi.cern.ch
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: ""
        hosts:
          - domain: cern.ch
            # hostOverride: panda-k8s-dev-jedi.cern.ch
