# iDDS configuration
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-envs
type: Opaque
stringData:
  MARIADB_DATABASE: "harvester"
  MARIADB_USER: "harvester"
  MARIADB_PASSWORD: {{ .Values.database.password }}
  MARIADB_ROOT_PASSWORD: {{ .Values.database.admin_password }}
  {{- if .Values.database.dbhost }}
  HARVESTER_DB_HOST: {{ .Values.database.dbhost }}
  {{- end }}

  PANDA_AUTH_ID_TOKEN: {{ .Values.global.authIdToken }}
  PANDA_AUTH_VO: {{ .Values.global.authVO }}
---
# certs
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-certs
type: Opaque
stringData:
  {{- range $path, $_ := .Files.Glob "cert/**.pem" }}
  {{ base $path }}: |-
    {{ $.Files.Get $path | b64enc }}
  {{- end }}
