{{- if .Values.persistentvolume.enabled -}}
# pv
kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ include "main.fullname" . }}-data
  labels:
      # dataType: data
      {{- include "main.labels" . | nindent 4 }}
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.persistentvolume.size }}
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{ .Values.persistentvolume.path }}
---
# pv claim
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "main.fullname" . }}-data
  labels:
    # dataType: data
    {{- include "main.labels" . | nindent 4 }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.persistentvolume.size }}
  selector:
    matchLabels:
      {{- include "main.selectorLabels" . | nindent 6 }}
---
{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "main.fullname" . }}
  labels:
    {{- include "main.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "main.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "main.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "main.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{ if .Values.autoStart -}}
          command: ["/bin/sh", "-c"]
          args:
            - /var/lib/artemis-instance/bin/artemis-service start;
              {{ $admin_name :=  .Values.admin.name }}
              {{ $admin_pass :=  .Values.admin.password }}
              {{- range .Values.users }}
              /var/lib/artemis-instance/bin/artemis user add --user-command-user {{.name}} --user-command-password {{.password}} --role {{.role}} --user {{ $admin_name}} --password {{ $admin_pass}}
              {{- end }}
              /var/lib/artemis-instance/bin/artemis-service stop;
              /var/lib/artemis-instance/bin/artemis run
          {{ end -}}
          ports:
            - name: port8161
              containerPort: 8161
              protocol: TCP
            - name: port5672
              containerPort: 5672
              protocol: TCP
            - name: port1883
              containerPort: 1883
              protocol: TCP
            - name: port61616
              containerPort: 61616
              protocol: TCP
            - name: port61613
              containerPort: 61613
              protocol: TCP
            - name: port9404
              containerPort: 9404
              protocol: TCP
            - name: port5445
              containerPort: 5445
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "main.fullname" . }}-configmap
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
              # - name: {{ include "main.fullname" . }}-logs
              #  mountPath: /var/log/activemq/
              - name: {{ include "main.fullname" . }}-data
                mountPath: /var/lib/artemis-instance
              # - name: {{ include "main.fullname" . }}-config
              #   mountPath: /opt/activemq/conf
              # - name: {{ include "main.fullname" . }}-configmap
              #   mountPath: /activemq/configmap
              - name: {{ include "main.fullname" . }}-sandbox
                mountPath: /opt/activemq-artemis/sandbox
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        # - name: {{ include "main.fullname" . }}-logs
        #   persistentVolumeClaim:
        #     claimName: {{ include "main.fullname" . }}-logs
        - name: {{ include "main.fullname" . }}-data
          persistentVolumeClaim:
            claimName: {{ include "main.fullname" . }}-data
        # - name: {{ include "main.fullname" . }}-conf
        #   persistentVolumeClaim:
        #     claimName: {{ include "main.fullname" . }}-conf
        # - name: {{ include "main.fullname" . }}-configmap
        #   configMap:
        #       name: {{ include "main.fullname" . }}-configmap
        - name: {{ include "main.fullname" . }}-sandbox
          configMap:
              name: {{ include "main.fullname" . }}-sandbox
