# iDDS configuration
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-db-envs
type: Opaque
stringData:
  MARIADB_USER: {{ .Values.database.user }}
  MARIADB_PASSWORD: {{ .Values.database.password }}
  MARIADB_ROOT_PASSWORD: {{ .Values.database.admin_password }}

---
# iam envs
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-iam-envs
type: Opaque
stringData:
  IAM_DB_HOST: {{.Values.database.host}}
  IAM_DB_NAME: {{.Values.database.name}}
  IAM_DB_USERNAME: {{.Values.database.user}}
  IAM_DB_PASSWORD: {{.Values.database.password}}
  IAM_CILOGON_CLIENT_ID: {{ .Values.cilogon.client_id}}
  IAM_CILOGON_CLIENT_SECRET: {{ .Values.cilogon.client_secret}}

---
# init db
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-initdb
type: Opaque
stringData:
  init_org_db.sql: |-
    CREATE DATABASE {{.Values.database.name}} CHARACTER SET latin1 COLLATE latin1_swedish_ci;
    GRANT ALL PRIVILEGES on {{.Values.database.name}}.* to '{{ .Values.database.user }}'@'%' identified by '{{ .Values.database.password }}';


