# Default values for activemq.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# activemq_db, activemq_user and activemq_schema should not be changed currently

main:
  enabled: true
  replicaCount: 1
  image:
    # repository: webcenter/activemq
    pullPolicy: "IfNotPresent"
    # Overrides the image tag whose default is the chart appVersion.
    # tag: "5.14.3"
    repository: wguanicedew/activemq-artemis
    tag: "0.0.2"
  autoStart: true

  persistentvolume:
    enabled: true
    # false for SLAC
    path: "/var/lib/artemis-instance"
    size: 5Gi
  hostcerts:
    enabled: false

  minmemory: 1024
  maxmemory: 2048
  scheduler:
    enabled: true
  auth:
    enabled: false

  admin:
    name: admin
    password: MyActiveMQPass0508
  users:
    - name: panda
      password: panda_pass
      role: panda
    - name: idds
      password: idds_pass
      role: idds
    - name: pilot
      password: pilot_pass
      role: pilot

  service:
    type: ClusterIP
  ingress:
    enabled: false
    hosts:
      - domain: cern.ch
        # hostOverride: activemq-k8s-dev-jedi.cern.ch
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: ""
        hosts:
          - domain: cern.ch
            # hostOverride: activemq-k8s-dev-jedi.cern.ch
