# Default values for ingress.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

traefik:
  replicaCount: 1

  image:
    name: traefik
    # defaults to appVersion
    tag: "2.8.1"

  globalArguments:
    - "--global.checknewversion"
    - "--global.sendanonymoususage"
    - "--log.level=DEBUG"

  service:
    enabled: true
    # type: LoadBalancer
    type: ClusterIP
    
    externalIPs:
      - 137.138.224.26

  # ingressClass:
  #   enabled: false

  nodeSelector:
    role: traefik

  providers:
    kubernetesCRD:
      enabled: true
    kubernetesIngress:
      enabled: true

  tlsOptions:
    tls12:
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384   # TLS 1.2
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305    # TLS 1.2
        - TLS_AES_256_GCM_SHA384                  # TLS 1.3
        - TLS_CHACHA20_POLY1305_SHA256            # TLS 1.3
      curvePreferences:
        - CurveP521
        - CurveP384
      sniStrict: false
      clientAuth:
        clientAuthType: RequestClientCert

  certResolvers:
    pandaResolver:
      email: wguan.icedew@gmail.com
      tlsChallenge: true
      httpChallenge:
        entryPoint: "idds"
      storage: "/tmp/acme.json"
      caserver: "https://acme-staging-v02.api.letsencrypt.org/directory"

  ports:
    traefik:
      port: 9000
      hostPort: 9000
      expose: true
      exposedPort: 9000
      protocol: TCP
    msgsvc:
      port: 61613
      hostPort: 61613
      expose: true
      exposedPort: 61613
      protocol: TCP
    web:
      port: 8000
      hostPort: 8000
      expose: true
      exposedPort: 8000
      protocol: TCP
    websecure:
      port: 8443
      hostPort: 8443
      expose: true
      exposedPort: 8443
      protocol: TCP
    idds:
      port: 7443
      hostPort: 7443
      expose: true
      exposedPort: 7443
      protocol: TCP
      tls:
        enabled: false
        # this is the name of a TLSOption definition
        options: ""
        certResolver: ""
        domains: []
    panda:
      port: 25443
      hostPort: 25443
      expose: true
      exposedPort: 25443
      protocol: TCP
    iam:
      port: 9443
      hostPort: 9443
      expose: true
      exposedPort: 9443
      protocol: TCP
    bigmon:
      port: 6443
      hostPort: 6443
      expose: true
      exposedPort: 6443
      protocol: TCP
