# service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-panda-server-service
  labels:
    app: panda-server
spec:
  type: ClusterIP     # NodePort
  ports:
   - name: panda-server-http
     protocol: TCP
     port: 25080
     targetPort: 25080
   - name: panda-server-https
     protocol: TCP
     port: 25443
     targetPort: 25443
  selector:
   app: panda-server
