apiVersion: v1
kind: Service
metadata:
  name: {{ include "daemon.fullname" . }}
  labels:
    {{- include "daemon.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "daemon.selectorLabels" . | nindent 4 }}
