# iDDS configuration
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-db-envs
type: Opaque
stringData:
  POSTGRES_DB: "{{ .Values.database.name }}"
  POSTGRES_USER: "{{ .Values.database.user }}"
  POSTGRES_PASSWORD: "{{ .Values.database.password }}"
  POSTGRES_SCHEMA: "{{ .Values.database.schema }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-envs
type: Opaque
stringData:
  PANDA_AUTH_ID_TOKEN: "{{ .Values.global.authIdToken }}"
  PANDA_AUTH_VO: "{{ .Values.global.authVO }}"
  PANDA_AUTH: "{{ .Values.global.auth }}"

  IDDS_DATABASE_NAME: "{{ .Values.database.name}}"
  IDDS_DATABASE_USER: "{{ .Values.database.user}}"
  IDDS_DATABASE_PASSWORD: "{{ .Values.database.password}}"
  IDDS_DATABASE_SCHEMA: "{{ .Values.database.schema}}"
  IDDS_DATABASE_HOST: "{{ .Values.database.host}}"

  IDDS_CONDUCTOR_BROKERS: "{{ join "," .Values.global.activemq.serverList }}"
  IDDS_CONDUCTOR_PORT: "{{default "61613" .Values.global.activemq.port}}"
  IDDS_CONDUCTOR_DESTINATION: "{{.Values.activemq.destination}}"
  IDDS_CONDUCTOR_USERNAME: "{{.Values.activemq.username}}"
  IDDS_CONDUCTOR_PASSWORD: "{{.Values.global.activemq.basePasswd}}_{{.Values.activemq.username}}"

  IDDS_OIDC_RUBIN_CLIENT_ID: "{{.Values.global.oidc.rubin.client_id}}"
  IDDS_OIDC_RUBIN_CLIENT_SECRET: "{{.Values.global.oidc.rubin.client_secret}}"
  IDDS_OIDC_RUBIN_PRODUCTION_CLIENT_ID: "{{.Values.global.oidc.rubin_production.client_id}}"
  IDDS_OIDC_RUBIN_PRODUCTION_CLIENT_SECRET: "{{.Values.global.oidc.rubin_production.client_secret}}"
  IDDS_OIDC_PANDA_DEV_CLIENT_ID: "{{.Values.global.oidc.panda_dev.client_id}}"
  IDDS_OIDC_PANDA_DEV_CLIENT_SECRET: "{{.Values.global.oidc.panda_dev.client_secret}}"

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-certs
type: Opaque
stringData:
  hostcert.pem: |-
{{ .Files.Get "hostcert.pem" | indent 4}}

  hostkey.pem: |-
{{ .Files.Get "hostkey.pem" | indent 4}}
