# "ported" by Adam Miller <maxamillion@fedoraproject.org> from
#   https://github.com/fedora-cloud/Fedora-Dockerfiles
#
# Originally written for Fedora-Dockerfiles by
#   scollier <scollier@redhat.com>

FROM centos:centos7
MAINTAINER The CentOS Project <cloud-ops@centos.org>

RUN yum -y update; yum clean all
RUN yum -y install sudo epel-release; yum clean all
RUN yum install -y https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
RUN yum install -y postgresql13-server pg_cron_13 pg_partman13 postgresql13-contrib; yum clean all
RUN yum -y install supervisor pwgen; yum clean all
# RUN yum -y install postgresql-server postgresql postgresql-contrib supervisor pwgen; yum clean all

RUN mkdir -p /usr/pgsql/
RUN ln -s /usr/pgsql-13/bin /usr/pgsql/bin

ADD ./postgresql-setup /usr/bin/postgresql-setup
# ADD ./supervisord.conf /etc/supervisord.conf
RUN mkdir /var/log/postgres
RUN chown postgres /var/log/postgres
ADD postgres.ini /etc/supervisord.d/
ADD ./start_postgres.sh /start_postgres.sh

#Sudo requires a tty. fix that.
RUN sed -i 's/.*requiretty$/#Defaults requiretty/' /etc/sudoers
RUN chmod +x /usr/bin/postgresql-setup
RUN chmod +x /start_postgres.sh

RUN /usr/bin/postgresql-setup initdb

# ADD ./postgresql.conf /var/lib/pgsql/data/postgresql.conf
RUN echo "password_encryption = md5" >> /var/lib/pgsql/data/postgresql.conf
RUN echo "listen_addresses = '*'" >> /var/lib/pgsql/data/postgresql.conf
RUN echo "shared_preload_libraries = 'pg_cron, pg_partman_bgw'" >> /var/lib/pgsql/data/postgresql.conf
RUN echo "cron.database_name = 'postgres'" >> /var/lib/pgsql/data/postgresql.conf
RUN echo "pg_partman_bgw.dbname = 'panda_db'" >> /var/lib/pgsql/data/postgresql.conf

RUN chown -v postgres.postgres /var/lib/pgsql/data/postgresql.conf

# RUN echo "host    all  all         0.0.0.0/0     md5" >> /var/lib/pgsql/data/pg_hba.conf
RUN echo "local   all  panda       trust" >> /var/lib/pgsql/data/pg_hba.conf
RUN echo "host    all  panda       localhost     trust" >> /var/lib/pgsql/data/pg_hba.conf
RUN echo "local   all  postgres    trust" >> /var/lib/pgsql/data/pg_hba.conf
RUN echo "host    all  postgres    localhost     trust" >> /var/lib/pgsql/data/pg_hba.conf
RUN echo "host    all  all         0.0.0.0/0     md5" >> /var/lib/pgsql/data/pg_hba.conf
RUN echo "host    all  all        ::0/0          md5" >> /var/lib/pgsql/data/pg_hba.conf

RUN ln -s /var/lib/pgsql /var/lib/postgresql
VOLUME ["/var/lib/postgresql/data"]

EXPOSE 5432

CMD ["/bin/bash", "/start_postgres.sh"]
