CREATE SCHEMA IF NOT EXISTS doma_deft;
ALTER SCHEMA doma_deft OWNER TO panda;

CREATE TABLE DOMA_DEFT.T_TASK
(
TASKID bigint NOT NULL,
PARENT_TID bigint ,
STATUS VARCHAR(12),
TOTAL_DONE_JOBS bigint ,
SUBMIT_TIME TIMESTAMP (0) NOT NULL,
START_TIME TIMESTAMP (0),
TIMESTAMP TIMESTAMP (0),
VO VARCHAR(16),
PRODSOURCELABEL VARCHAR(20),
TASKNAME VARCHAR(256),
USERNAME VARCHAR(128),
PRIORITY bigint ,
CURRENT_PRIORITY bigint ,
TOTAL_REQ_JOBS bigint ,
CHAIN_TID bigint ,
TOTAL_EVENTS bigint ,
JEDI_TASK_PARAMETERS TEXT ,
TOTAL_INPUT_EVENTS bigint ,
  CONSTRAINT T_TASK_TASKID_NN CHECK (TASKID IS NOT NULL),
  CONSTRAINT T_TASK_SUBMIT_TIME_NN CHECK (SUBMIT_TIME IS NOT NULL)
)
;

ALTER TABLE DOMA_DEFT.T_TASK OWNER TO panda;
CREATE UNIQUE INDEX T_TASK_PK_PART ON DOMA_DEFT.T_TASK (TASKID);
CREATE INDEX T_TASK_STATUS_PRODLABEL_IDX ON DOMA_DEFT.T_TASK (STATUS, PRODSOURCELABEL);
CREATE INDEX T_TASK_TASKNAME_IDX ON DOMA_DEFT.T_TASK (TASKNAME);
CREATE INDEX T_TASK_USERNAME_IDX ON DOMA_DEFT.T_TASK (USERNAME);

CREATE TABLE DOMA_DEFT.PRODSYS_COMM
(
COMM_TASK bigint NOT NULL,
COMM_META bigint ,
COMM_OWNER VARCHAR(16),
COMM_CMD VARCHAR(256),
COMM_TS bigint ,
COMM_COMMENT VARCHAR(128),
COMM_PARAMETERS TEXT
)
;

ALTER TABLE DOMA_DEFT.PRODSYS_COMM OWNER TO panda;

CREATE SEQUENCE DOMA_DEFT.prodsys2_task_id_seq INCREMENT 1 MINVALUE 1 NO MAXVALUE START 1;
ALTER SEQUENCE DOMA_DEFT.prodsys2_task_id_seq OWNER TO panda;
