-- Generated by Ora2Pg, the Oracle database Schema converter, version 21.1
-- Copyright 2000-2020 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:INT8R

SET client_encoding TO 'UTF8';

SET search_path = doma_pandabigmon,public;
\set ON_ERROR_STOP ON

SET check_function_bodies = false;


CREATE TYPE job_t AS (
PANDAID bigint   
, JOBDEFINITIONID bigint 
, SCHEDULERID varchar(128) 
, PILOTID varchar(200) 
, CREATIONTIME timestamp  
, CREATIONHOST varchar(128) 
, MODIFICATIONTIME timestamp 
, MODIFICATIONHOST varchar(128) 
, ATLASRELEASE varchar(64) 
, TRANSFORMATION varchar(250) 
, HOMEPACKAGE varchar(80) 
, PRODSERIESLABEL varchar(20) 
, PRODSOURCELABEL varchar(20) 
, PRODUSERID varchar(250) 
, ASSIGNEDPRIORITY numeric 
, CURRENTPRIORITY numeric   
, ATTEMPTNR smallint 
, MAXATTEMPT smallint 
, JOBSTATUS varchar(15) 
, JOBNAME varchar(256) 
, MAXCPUCOUNT bigint   
, MAXCPUUNIT varchar(32) 
, MAXDISKCOUNT bigint 
, MAXDISKUNIT char(4) 
, IPCONNECTIVITY char(5) 
, MINRAMCOUNT bigint 
, MINRAMUNIT char(4) 
, STARTTIME timestamp  
, ENDTIME timestamp 
, CPUCONSUMPTIONTIME bigint 
, CPUCONSUMPTIONUNIT varchar(128) 
, COMMANDTOPILOT varchar(250) 
, TRANSEXITCODE varchar(128) 
, PILOTERRORCODE numeric 
, PILOTERRORDIAG varchar(500) 
, EXEERRORCODE numeric 
, EXEERRORDIAG varchar(500) 
, SUPERRORCODE numeric 
, SUPERRORDIAG varchar(250) 
, DDMERRORCODE numeric 
, DDMERRORDIAG varchar(500) 
, BROKERAGEERRORCODE numeric 
, BROKERAGEERRORDIAG varchar(250) 
, JOBDISPATCHERERRORCODE numeric 
, JOBDISPATCHERERRORDIAG varchar(250) 
, TASKBUFFERERRORCODE numeric 
, TASKBUFFERERRORDIAG varchar(300) 
, COMPUTINGSITE varchar(128) 
, COMPUTINGELEMENT varchar(128) 
, JOBPARAMETERS text 
, METADATA text 
, PRODDBLOCK varchar(255) 
, DISPATCHDBLOCK varchar(255) 
, DESTINATIONDBLOCK varchar(255) 
, DESTINATIONSE varchar(250) 
, NEVENTS bigint 
, GRID varchar(50) 
, CLOUD varchar(50) 
, CPUCONVERSION decimal(9,4) 
, SOURCESITE varchar(36) 
, DESTINATIONSITE varchar(36) 
, TRANSFERTYPE varchar(10) 
, TASKID numeric 
, CMTCONFIG varchar(250) 
, STATECHANGETIME timestamp 
, PRODDBUPDATETIME timestamp 
, LOCKEDBY varchar(128) 
, RELOCATIONFLAG smallint 
, JOBEXECUTIONID bigint 
, VO varchar(16) 
, PILOTTIMING varchar(100) 
, WORKINGGROUP varchar(20) 
, PROCESSINGTYPE varchar(64) 
, PRODUSERNAME varchar(60) 
, NINPUTFILES numeric 
, COUNTRYGROUP varchar(20) 
, BATCHID varchar(80) 
, PARENTID bigint 
, SPECIALHANDLING varchar(80) 
, JOBSETID bigint 
, CORECOUNT smallint 
, NINPUTDATAFILES numeric 
, INPUTFILETYPE varchar(32) 
, INPUTFILEPROJECT varchar(64) 
, INPUTFILEBYTES bigint 
, NOUTPUTDATAFILES numeric 
, OUTPUTFILEBYTES bigint 
, JOBMETRICS varchar(500) 
, WORKQUEUE_ID numeric 
, JEDITASKID bigint 
, JOBSUBSTATUS varchar(80) 
, ACTUALCORECOUNT numeric 
, REQID numeric 
, NEWPANDAID bigint

);
ALTER TYPE job_t OWNER TO panda;


CREATE TYPE hs06s_t AS (
NUCLEUS varchar(200)
, COMPUTINGSITE  varchar(200)
, USEDHS06SPERSITE bigint
, FAILEDHS06SPERSITE bigint

);
ALTER TYPE hs06s_t OWNER TO panda;


CREATE TYPE hs06stot_t AS (
NUCLEUS varchar(200)
, NTASKSPERNUCLEUS bigint
, TOTHS06SPERNUCLEUS bigint


);
ALTER TYPE hs06stot_t OWNER TO panda;



CREATE TYPE chainjsonrow_t AS (
NUCLEUS varchar(10000)

);
ALTER TYPE chainjsonrow_t OWNER TO panda;


CREATE TYPE taskprofile_obj AS (
ENDTIME timestamp
, STARTTIME  timestamp
, NEVENTS bigint
, NJOB bigint

);
ALTER TYPE taskprofile_obj OWNER TO panda;

CREATE TYPE jobstable_t AS (jobstable_t JOB_T[]);
ALTER TYPE jobstable_t OWNER TO panda;

CREATE TYPE hs06ssummary_t AS (hs06ssummary_t HS06S_T[]);
ALTER TYPE hs06ssummary_t OWNER TO panda;

CREATE TYPE hs06stotsummary_t AS (hs06stotsummary_t HS06STOT_T[]);
ALTER TYPE hs06stotsummary_t OWNER TO panda;


CREATE TYPE chainjsontable_t AS (chainjsontable_t CHAINJSONROW_T[]);
ALTER TYPE chainjsontable_t OWNER TO panda;

CREATE TYPE taskprofile_coll AS (taskprofile_coll TASKPROFILE_OBJ[]);
ALTER TYPE taskprofile_coll OWNER TO panda;


CREATE TYPE jobs_obj AS (
attr varchar(4000),
  attr_val varchar(4000),
  cnt bigint

);
ALTER TYPE jobs_obj OWNER TO panda;

CREATE TYPE jobs_tab AS (jobs_tab jobs_obj[]);
ALTER TYPE jobs_tab OWNER TO panda;


CREATE TYPE jobs_attr_obj AS (
ATLASRELEASE	varchar(64),
  ATTEMPTNR	smallint,
  COMPUTINGSITE	varchar(128),
  CLOUD	varchar(50),
  EVENTSERVICE	smallint,
  HOMEPACKAGE	varchar(80),
  INPUTFILEPROJECT	varchar(64),
  INPUTFILETYPE	varchar(32),
  JEDITASKID	bigint,
  JOBSTATUS	varchar(15),
  JOBSUBSTATUS	varchar(80),
  MINRAMCOUNT	bigint,
  NUCLEUS	varchar(52),
  PROCESSINGTYPE	varchar(64),
  PRODSOURCELABEL	varchar(20),
  PRODUSERNAME	varchar(60),
  REQID	numeric,
  TRANSFORMATION	varchar(250),
  WORKINGGROUP	varchar(20)

);
ALTER TYPE jobs_attr_obj OWNER TO panda;

CREATE TYPE jobs_attr_tab AS (jobs_attr_tab jobs_attr_obj[]);
ALTER TYPE jobs_attr_tab OWNER TO panda;


 CREATE TYPE pandamon_jobpage_obj AS (
     PANDA_ATTRIBUTE VARCHAR(100),
     ATTR_VALUE VARCHAR(300),
     NUM_OCCURRENCES bigint
 );
 ALTER TYPE pandamon_jobpage_obj OWNER TO panda;

 CREATE TYPE pandamon_jobspage_coll AS (pandamon_jobspage_coll pandamon_jobpage_obj[]);
 ALTER TYPE pandamon_jobspage_coll OWNER TO panda;
 
