secret:
  name: panda-dev-secret

authIdToken: "FIXME"

# VO (. role) of the ID token
authVO: "Rubin.production"

database:
  password: FIXME
  dbhost: "panda-dev-postgres"

activemq:
  # hosts and ports
  serverList:
    - "activemq-dev:61613"

  # base password
  basePasswd: "FIXME"

# iDDS
idds:
  # REST hostname
  restHost: "idds-rest"

  # REST port
  restPort: 443

  # ID token of the iDDS account
  authIdToken: "FIXME"

  # VO of the ID token
  authVO: "panda_dev"

# rucio
rucio:
  # rucio host and port
  rucioHost: "sprucio01.sdcc.bnl.gov:443"

  # auth host and port
  authHost: "sprucio01.sdcc.bnl.gov:443"

  # username
  username: "iddsv1"

  # password
  password: "FIXME"

  # account
  account: "iddsv1"
