name: Bug Report
description: Create a report to help us improve.
labels: ['status/0-needs-triage']
body:
  - type: markdown
    attributes:
      value: |
        ### How to write a good bug report?

        - Respect the issue template as much as possible.
        - The title should be short and descriptive.
        - Explain the conditions which led you to report this issue: the context.
        - The context should lead to something, an idea or a problem that you’re facing.
        - Remain clear and concise.
        - Format your messages to help the reader focus on what matters and understand the structure of your message, use [Markdown syntax](https://help.github.com/articles/github-flavored-markdown)

  - type: checkboxes
    id: terms
    attributes:
      label: Welcome!
      options:
        - label: Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
          required: true
        - label: Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.
          required: true

  - type: input
    attributes:
      label: What version of the Traefik's Helm Chart are you using?
      description: |
        `latest` is not considered as a valid version.
        We need a release number!
      placeholder: Your version here.
    validations:
      required: true

  - type: input
    attributes:
      label: What version of Traefik are you using?
      description: |
        `latest` is not considered as a valid version.
        We need a release number!
      placeholder: Your version here.
    validations:
      required: true

  - type: textarea
    attributes:
      label: What did you do?
      description: Use [Markdown syntax](https://help.github.com/articles/github-flavored-markdown) if needed.
      placeholder: What did you do?
    validations:
      required: true

  - type: textarea
    attributes:
      label: What did you see instead?
      description: Use [Markdown syntax](https://help.github.com/articles/github-flavored-markdown) if needed.
      placeholder: What did you see instead?
    validations:
      required: true

  - type: textarea
    attributes:
      label: What is your environment & configuration?
      description: |
        platform, arguments, YAML, TOML, platform, etc.

        Use [Markdown syntax](https://help.github.com/articles/github-flavored-markdown) if needed.
      placeholder: Add information here.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional Information
      description: Use [Markdown syntax](https://help.github.com/articles/github-flavored-markdown) if needed.
      placeholder: Add information here.
      render: shell
    validations:
      required: false
