apiVersion: v1
kind: Service
metadata:
  name: {{ include "idds.fullname" . }}
  labels:
    {{- include "idds.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "idds.selectorLabels" . | nindent 4 }}
