# iDDS configuration
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}-envs
type: Opaque
stringData:
  PANDA_DB_PASSWORD: {{ .Values.database.password }}
  PANDA_DB_HOST: {{ .Values.database.dbhost }}
  PANDA_AUTH_ID_TOKEN: {{ .Values.authIdToken }}
  PANDA_AUTH_VO: {{ .Values.authVO }}

  # ActiveMQ
  PANDA_ACTIVEMQ_LIST: {{ join "," .Values.activemq.serverList }}
  PANDA_ACTIVEMQ_PASSWD_panda: {{ .Values.activemq.basePasswd }}_panda
  PANDA_ACTIVEMQ_PASSWD_jedi: {{ .Values.activemq.basePasswd }}_jedi

  # iDDS
  PANDA_IDDS_HOST: "{{ .Values.idds.restHost }}"
  PANDA_IDDS_PORT: "{{ .Values.idds.restPort }}"
  PANDA_IDDS_AUTH_ID_TOKEN: "{{ .Values.idds.authIdToken }}"
  PANDA_IDDS_AUTH_VO: "{{ .Values.idds.authVO }}"
  
  # Rucio
  PANDA_RUCIO_HOST: "{{ .Values.rucio.rucioHost }}"
  PANDA_RUCIO_AUTH_HOST: "{{ .Values.rucio.authHost }}"
  PANDA_RUCIO_USERNAME: "{{ .Values.rucio.username }}"
  PANDA_RUCIO_PASSWORD: "{{ .Values.rucio.password }}"
  PANDA_RUCIO_ACCOUNT: "{{ .Values.rucio.account }}"

---
# certs
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}-certs
type: Opaque
stringData:
  {{- range $path, $_ := .Files.Glob "cert/**.pem" }}
  {{ base $path }}: |-
    {{ $.Files.Get $path | b64enc }}
  {{- end }}

---
# auth
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}-auth
type: Opaque
stringData:
  {{- range $path, $_ := .Files.Glob "auth/**_auth_config.json" }}
  {{ base $path }}: |-
    {{ $.Files.Get $path }}
  {{- end }}
