{{- if .Values.harvester.enabled }}
# harvester configuration
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.harvester.name }}-envs
type: Opaque
stringData:
  MARIADB_DATABASE: "harvester"
  MARIADB_USER: "harvester"
  MARIADB_PASSWORD: {{ .Values.harvester.database.password }}
  MARIADB_ROOT_PASSWORD: {{ .Values.harvester.database.admin_password }}
  HARVESTER_DB_HOST: {{ .Values.harvester.database.dbhost }}

  PANDA_AUTH_ID_TOKEN: {{ .Values.auth.authIdToken }}
  PANDA_AUTH_VO: {{ .Values.auth.authVO }}
  PANDA_BEHIND_REAL_LB: "1"
  PANDA_URL: "{{ .Values.panda.url}}"
  PANDA_URL_SSL: "{{ .Values.panda.urlSSL}}"

  {{- if .Values.harvester.experiment }}
  EXPERIMENT: {{ .Values.harvester.experiment }}
  {{- end}}

  HARVESTER_ID: "{{ .Values.harvester.harvesterID }}"
  {{ if .Values.harvester.useStableCondor }}
  CONDOR_CHANNEL: ".stable"
  {{- end }}

---
# certs
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.harvester.name }}-certs
type: Opaque
stringData:
  {{- range $path, $_ := .Files.Glob "files/harvester_certs/**.pem" }}
  {{ base $path }}: |-
    {{ $.Files.Get $path | b64enc }}
  {{- end }}

{{- end }}
