{{- if .Values.msgsvc.enabled }}
# msgsvc configuration
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.msgsvc.name }}-envs
type: Opaque
stringData:
  ACTIVEMQ_BASE_PASSWD: {{ .Values.msgsvc.basePasswd }}
  ACTIVEMQ_CHANNELS: {{ join ";" .Values.msgsvc.channels }}
  ACTIVEMQ_ACCOUNTS: {{ join ";" .Values.msgsvc.accounts }}

{{- end }}
