{{- if .Values.panda.enabled }}
# panda configuration
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.panda.name }}-envs
type: Opaque
stringData:
  PANDA_DB_PASSWORD: {{ .Values.panda.database.password }}
  PANDA_DB_HOST: {{ .Values.panda.database.dbhost }}

  PANDA_URL: "{{ .Values.panda.url}}"
  PANDA_URL_SSL: "{{ .Values.panda.urlSSL}}"
  PANDA_VERIFY_HOST: "off"
  PANDA_AUTH: "oidc"
  PANDA_AUTH_ID_TOKEN: {{ .Values.auth.authIdToken }}
  PANDA_AUTH_VO: {{ .Values.auth.authVO }}

  PANDA_SANDBOX_HOST: "{{ .Values.panda.hostName }}"

  # ActiveMQ
  PANDA_ACTIVEMQ_LIST: {{ join "," .Values.msgsvc.serverList }}
  PANDA_ACTIVEMQ_PASSWD_panda: {{ .Values.msgsvc.basePasswd }}_panda
  PANDA_ACTIVEMQ_PASSWD_jedi: {{ .Values.msgsvc.basePasswd }}_jedi

  # iDDS
  PANDA_IDDS_HOST: "{{ .Values.idds.restHost }}"
  PANDA_IDDS_PORT: "{{ .Values.idds.restPort }}"
  PANDA_IDDS_AUTH_ID_TOKEN: "{{ .Values.auth.authIdToken }}"
  PANDA_IDDS_AUTH_VO: "{{ .Values.auth.authVO }}"
  
  # Rucio
  PANDA_RUCIO_HOST: "{{ .Values.rucio.rucioHost }}"
  PANDA_RUCIO_AUTH_HOST: "{{ .Values.rucio.authHost }}"
  PANDA_RUCIO_USERNAME: "{{ .Values.rucio.username }}"
  PANDA_RUCIO_PASSWORD: "{{ .Values.rucio.password }}"
  PANDA_RUCIO_ACCOUNT: "{{ .Values.rucio.account }}"

---
# certs
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.panda.name }}-certs
type: Opaque
stringData:
  {{- range $path, $_ := .Files.Glob "files/panda_certs/**.pem" }}
  {{ base $path }}: |-
    {{ $.Files.Get $path | b64enc }}
  {{- end }}

---
# auth
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.panda.name }}-auth
type: Opaque
stringData:
  {{- range $client := .Values.auth.oidc.clients }}
  {{ $client.name }}_auth_config.json: |-
    {{ $.Files.Get "files/panda_auths/auth_config.json.template" | replace "ID" $client.client_id | replace "SECRET" $client.client_secret | replace "URL" $.Values.auth.oidc.config_url | replace "AUDIENCE" $.Values.auth.oidc.audience  | replace "VO" $client.name }}
  {{ end }}

{{- end }}
