configmap:
  name: idds-dev

database:
  name: "idds_db"
  user: "idds"
  password: "MyPass0508"
  schema: "doma_idds"
  host: ""

oidc:
    atlas:
      client_id: abc
      client_secret: abc
    rubin:
      client_id: "e83c3301-a918-4ddb-9937-40375034af6a"
      client_secret: "AKJxrDlUeXUoT9RCy7dfg25lvHEqYpHk5GEghIKAFKVxDHpaViGMswkaebdiMpYDn-KV6xjtbX4jbpuymClrcXY"
    rubin_production:
      client_id: "be00a534-5772-4676-b594-47d05fe24fce"
      client_secret: "VrQgIXAJrYhMV4yfhLuMf71vfppNfZxgDblCRX1DD77paCOXPXnbrbrBFtdq5lnv_fjtusU96RxQzWPwlOK7CA"
    panda_dev:
      client_id: "e83c3301-a918-4ddb-9937-40375034af6a"
      client_secret: "AKJxrDlUeXUoT9RCy7dfg25lvHEqYpHk5GEghIKAFKVxDHpaViGMswkaebdiMpYDn-KV6xjtbX4jbpuymClrcXY"

conductor:
    brokers: activemq-dev
    port: 61613
    destination: /queue/iddspanda
    username: FIXME_WRITER
    password: FIXME_PASS

authToken: '{"access_token":"eyJraWQiOiJyc2ExIiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJmMDhhNmFmYy1mOWJkLTRlMWMtYTA3Mi00YjFhNTYxNjU3YjUiLCJpc3MiOiJodHRwczpcL1wvcGFuZGEtaWFtLWRvbWEuY2Vybi5jaCIsIm5hbWUiOiJXZW4gR3VhbiIsImdyb3VwcyI6WyJSdWJpbiIsIlJ1YmluXC9wcm9kdWN0aW9uIiwicGFuZGFfZGV2Il0sInByZWZlcnJlZF91c2VybmFtZSI6IndndWFuIiwib3JnYW5pc2F0aW9uX25hbWUiOiJQYW5EQS1ET01BIiwiaWF0IjoxNjUzMjE5Nzg4LCJqdGkiOiI3OTU3MTRjMy1hNGU1LTQxYTAtODllYS0zNmY0NTU3NjY0NzMiLCJjbGllbnRfaWQiOiJiZTAwYTUzNC01NzcyLTQ2NzYtYjU5NC00N2QwNWZlMjRmY2UiLCJlbWFpbCI6Ildlbi5HdWFuQGNlcm4uY2gifQ.Ui_VKnCr-zmTa305sQyyvBpi5D6sYfUIBPTIAEmOUMTeeYTkGT0rABCN9hn2VqxrfZs4XTg9lOzOnoR6fgFf1ldODTpuGq3O06gBWWQvYz_HsrgfsmgoF0Oo0E7Q_Gy7J5TV1eGubgoRXcLfleuhZnRMV5vNo_QGm9FqxJLHWLk","token_type":"Bearer","refresh_token":"eyJhbGciOiJub25lIn0.eyJqdGkiOiIyZGY2MjFlZS1lYzU4LTRlOTAtOGRkNi0xNTFkODcyNTc5N2QifQ.","scope":"email openid offline_access profile","id_token":"eyJraWQiOiJyc2ExIiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJmMDhhNmFmYy1mOWJkLTRlMWMtYTA3Mi00YjFhNTYxNjU3YjUiLCJhdWQiOiJiZTAwYTUzNC01NzcyLTQ2NzYtYjU5NC00N2QwNWZlMjRmY2UiLCJraWQiOiJyc2ExIiwiaXNzIjoiaHR0cHM6XC9cL3BhbmRhLWlhbS1kb21hLmNlcm4uY2hcLyIsIm5hbWUiOiJXZW4gR3VhbiIsImdyb3VwcyI6WyJSdWJpbiIsIlJ1YmluXC9wcm9kdWN0aW9uIiwicGFuZGFfZGV2Il0sInByZWZlcnJlZF91c2VybmFtZSI6IndndWFuIiwib3JnYW5pc2F0aW9uX25hbWUiOiJQYW5EQS1ET01BIiwiZXhwIjoxNjg0NzU1Nzg4LCJpYXQiOjE2NTMyMTk3ODgsImp0aSI6IjQ5Nzk5NWMzLTNjMzYtNGNiNC04ZWYwLWU2NzZhY2Y3ZWI4NCIsImVtYWlsIjoiV2VuLkd1YW5AY2Vybi5jaCJ9.IjZqzi-A214CVsEwVB-NRbrT499AI54SdofyMKBD7rFp01SN_sMpMldw7BeK4w6pUBG9TL6kfWY21eto1m_o8oa4lA-qjNdGzMFH6ZhDBN9DN6sjafp9OR60CNG66oxo13GPNV9JS6v67-rvLcKK-QfnBkQ7sAGqDNx5SONvOoc"}' 

panda:
  panda_url_ssl: https://panda-dev-server:443/server/panda
  panda_url: http://panda-dev-server:80/server/panda
  panda_monitor_url: "https://panda-dev-server"
  panda_auth: "oidc"
  panda_auth_vo: "Rubin:production"
  panda_config_root: "/opt/idds/config/"
  pandacache_url: "https://panda-dev-server:443/server/panda"
  panda_verify_host: "off"
